apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vapi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vapi
    app.kubernetes.io/part-of: vapi
  name: vapi
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/instance: vapi
status:
  loadBalancer: {}
